/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'cpp_cortex_M0_library' 
 * Target:  'FRDM-KL05ZJ' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "MKL05Z4.h"



#endif /* RTE_COMPONENTS_H */
